import type { Metadata } from "next";
import HeaderComponent from "@components/layout/header";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen max-h-screen overflow-hidden flex flex-col gap-4">
      <HeaderComponent />
      <div className=" container mx-auto md:p-6 p-4 ">
      {children}
      </div>
    </div>
  );
}
